---
plugin: aws_ec2

regions:
  - ap-south-1

filters:
  tag:Environment: production
  tag:Role: webserver
  tag:Project: ansible-nginx
  instance-state-name: running

# FIX — public-ip-address ki jagah ip-address
hostnames:
  - ip-address

keyed_groups:
  - key: tags.Environment
    prefix: env
  - key: tags.Role
    prefix: role

compose:
  ansible_host: public_ip_address